# Generated by Django 4.2 on 2023-05-16 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teams', '0004_alter_teamstatistic_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения матча')),
                ('place', models.CharField(max_length=150, verbose_name='Место проведения матча')),
                ('season', models.PositiveIntegerField(verbose_name='Номер сезона')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Завершен ли матч')),
                ('team_1_goals', models.PositiveIntegerField(default=0, verbose_name='Количество очков первой команды')),
                ('team_2_goals', models.PositiveIntegerField(default=0, verbose_name='Количество очков второй команды')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1_matches', to='Teams.team')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2_matches', to='Teams.team')),
            ],
        ),
    ]
