# Generated by Django 4.2 on 2023-05-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_articleimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120, verbose_name='Название компании')),
                ('partner_description', models.TextField(verbose_name='Описание партнёра')),
                ('partner_site_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на сайт партнёра')),
            ],
        ),
    ]
