# Generated by Django 4.2 on 2023-05-19 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='photo',
            field=models.ImageField(blank=True, upload_to='partners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Превью поста'),
        ),
    ]
