# Generated by Django 4.2 on 2023-05-12 11:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название команды')),
            ],
        ),
        migrations.CreateModel(
            name='TeamStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_games', models.IntegerField(blank=True, default=0, verbose_name='Сыграно игр')),
                ('wins', models.IntegerField(blank=True, default=0, verbose_name='Победы')),
                ('draws', models.IntegerField(blank=True, default=0, verbose_name='Ничьи')),
                ('losses', models.IntegerField(blank=True, default=0, verbose_name='Поражения')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('last_name', models.TextField(verbose_name='Фамилия')),
                ('middle_name', models.TextField(blank=True, null=True, verbose_name='Отчество')),
                ('photo', models.ImageField(blank=True, upload_to='player_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Фото игрока')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teams.team', verbose_name='Команда игрока')),
            ],
        ),
    ]
