# Generated by Django 4.2 on 2023-05-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstatistic',
            name='players',
            field=models.ManyToManyField(to='Teams.player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Название команды'),
        ),
    ]
