# Generated by Django 4.2 on 2023-05-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0002_teamstatistic_players_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstatistic',
            name='logo',
            field=models.ImageField(blank=True, upload_to='teams/logos/'),
        ),
        migrations.AddField(
            model_name='teamstatistic',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=120, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='player',
            name='middle_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Имя'),
        ),
    ]
