# Generated by Django 4.2 on 2023-05-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0003_teamstatistic_logo_teamstatistic_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamstatistic',
            name='players',
            field=models.ManyToManyField(blank=True, to='Teams.player'),
        ),
    ]
