# Generated by Django 4.2 on 2023-05-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0005_player_height_player_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamstatistic',
            name='players',
        ),
    ]
