# Generated by Django 4.2 on 2023-04-08 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Команды')),
                ('team_name', models.CharField(max_length=255, verbose_name='Название команды')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Игрока')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='Фамилия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Statistics.team', verbose_name='ID Команды')),
            ],
        ),
    ]
