# Generated by Django 4.2 on 2023-04-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Игрока'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Команды'),
        ),
    ]
