# Generated by Django 4.2 on 2023-04-14 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0002_player_reg_date_alter_player_player_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamed_played', models.IntegerField(default=0, verbose_name='Сыграно игр')),
                ('total_score', models.IntegerField(default=0, verbose_name='Всего очков')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Statistics.player', verbose_name='ID игрока')),
            ],
        ),
    ]
