# Generated by Django 4.2 on 2023-04-14 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0003_playerstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstats',
            old_name='gamed_played',
            new_name='games_played',
        ),
    ]
