# Generated by Django 4.2 on 2023-04-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0004_rename_gamed_played_playerstats_games_played'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstats',
            old_name='player_id',
            new_name='player',
        ),
    ]
